apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test1371
  name: mpts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mpts
  template:
    metadata:
      labels:
        app: mpts
    spec:
      restartPolicy: Always
      containers:
      - name: spirit
        image: 10.18.10.10:5000/xiaobr/other/mpts:2.7.3
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 6379 # Redis port
          - containerPort: 10011 # Ice port
          - containerPort: 8080 # Tomcat port

        resources:
          requests:
            cpu: 1500m
            memory: 1024Mi
      - name: spirit-server
        image: 10.18.10.10:5000/xiaobr/other/py_36_no_backpack:v0.0.4
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 6358
---
apiVersion: v1
kind: Service
metadata:
  namespace: test1371
  name: mpts
spec:
  ports:
  - name: ice
    protocol: TCP
    port: 6358
    targetPort: 6358
  selector:
    app: mpts
  clusterIP: 170.16.64.204
