# --- Algorithm specific parameters ---

use_local_action : False
red_agent: 'whw'
hidden_size: 64
max_time: 20000
use_gae: True
use_popart: False
use_valuenorm: True
use_proper_time_limits: False

adv: pg
train_ratio: 0.5
n_embd: 64
n_head: 1
n_block: 1
use_rule: True

device : "cuda"
only_step: False
lr: 0.0005
critic_lr: 0.0005
opti_eps: 0.00001
weight_decay: 0
who_coef: 0.1
entropy_coef: 0.005
clip_param: 0.05
ppo_epoch: 15
value_loss_coef: 1.0
max_grad_norm: 10.0
use_max_grad_norm: True
huber_delta: 10.0
use_huber_loss: True
use_clipped_value_loss: True
batch_size: 64
models_type: ["transformer"]
test_interval : 3
test_episode : 3
flight_control_frequency : 3700  # 飞机控制频率
load_model_path: 'models/whw/2022_04_09_23_59_16/ep_10_0.009523809523809525_0.4987301587301588'
# ---- TODO: 重要的开关参数 ----
#train_ship_only : False  # 是否只训练船
#use_learned_ship_model : True  # 是否采用ship模型learn到的位置
#enable_staged_combat : True
#no_op_action_priority : 8
#use_tree_agent : False
## --- Debug ---
#debug : True
## --- Env ---
#flight_control_frequency : 3700  # 飞机控制频率
#
## args.device = "cuda" if args.use_cuda else "cpu"
#use_cuda : False
#device : "cpu"
##use_cuda : True
## device : "cuda"
#
#n_agents : 2  #原来是4?
#
## --- state space ---
#enable_relative_representation : True  # TODO:针对研究点1：是否采用“类似卷积”的方式对所有agents的observation做处理
#agent : "rnn"
#obs_last_action : True
#obs_agent_id : False
#state_shape : 832
#obs_shape : 1216
## state_shape : 72
## obs_shape : 72
#
#
## args.n_actions = (36 + 2 if not USE_LOCAL_ACTION else 18 + 2) if not args.train_ship_only else 18
##train_ship_only : True  # 只训练船
## n_actions : 18
#
##train_ship_only : False  # 船、飞机都训练
## use_local_action : True
## n_actions : 20
## use_local_action : False
#n_actions : 38
#
#
#
## --- action selector ---
#action_selector : "epsilon_greedy"
#epsilon_start : 0.8
#epsilon_finish : 0.02
#epsilon_anneal_time : 200  # TODO: 单位: episode
#
## --- Optimizer ---
#optimizer : "RMS"
#optim_alpha : 0.99  # RMSProp alpha
#optim_eps : 0.00001  # RMSProp epsilon
#grad_norm_clip : 10  # Reduce magnitude of gradients above this L2 norm
#
## --- RL hyperparameters ---
#batch_size_run : 1
#gamma : 0.99
#target_update_interval : 80  # 4 个episode更新一次（40 actors）
#episode_limit : 6
## -- NN parameters --
#rnn_hidden_dim : 64
## -- Mixer --
#name : "qmix"
#mixer : "qmix"
#agent_output_type : "q"
#learner : "q_learner"
#double_q : True
#mixing_embed_dim : 32  # 64
#hypernet_layers : 2
#hypernet_embed : 64  # 128
## -- Buffer --
#buffer_size : 500  # 1000条轨迹
#buffer_cpu_only : True
#prioritized : False
## ---- Train Ship ----
#ship_agent_num : 14
#ship_action_num : 18
#ship_qmix_embedding_dim : 128
#ship_buffer_size : 5000
#enable_multi_row : True
#row_num_of_qtable : 1
## ---- Logger ----
#runner_log_interval : 1  # Log runner stats (not test stats) every {} episodes 画图: train return (mean,std)
#learner_log_interval : 2  # Log training stats every {} episodes  画图：train loss
#
## 蓝方对手
#opponent_plan_num : 5
#
## 多场景训练时，训练的区域
#train_area_list : []
