# --- Defaults ---

# log
use_log: True
log_to_cmd : False
log_to_file : True
log_to_tensorboard : False
log_save_model: True
time_str: "%Y_%m_%d_%H_%M_%S"
use_tree_agent: True

use-tensorboard: True
use_cuda: False

# sample
# num_sample_max : 10000
num_sample_max : 5000
num_sample_every_trun : 1  # 每次训练前采样的总数目
sample_log_interval : 1

# learn
num_learn_max : 1000000
time_learn_control_sleep : 1 # 如果buffer中数据未达标，则等待的时间。
num_learn_every_trun : 1  # 每个采样轮次结束，连续训练的次数
train_log_interval : 1  # Log summary of stats after every {} episodes TODO: 画图画Episode
batch_size : 1 #64 # 32
use_popart: True

# test
test_episode : 20 # 20 # Number of episodes to test for TODO: 画图画 test return (mean,std)
test_interval : 50 #100 # Test after {} episodes have passed
# num_test_every_learn_batch : 100
# load and save
save_model_interval : 4  # Save models after this many episodes
# 是否要加载之前训练的“飞机”模型
load_model_path : "./red/models/task_detection/2022_02_25_09_12_40/ep_1650_10_15/"
# 只供训练用：训练飞机的时候，“舰船”模型的位置必须提供（在sampler中被初始化）
load_ship_model_path : ""

# env
sim_time :  50400
# episode-num", type=int, default=10000, help="number of episodes")
env_type: ''
scenario: 'scenario_one'
episode_num: 10
# 测试用, 测试局数
dist_type: 'pc'
task: 'task_detection'
algs_type: 'whw'
red_agent: 'whw'
blue_agent: 'zc1'
